database_info:
  host: shortline.proxy.rlwy.net
  public_port: 24046
  database: railway
  user: root
  password: TyeCtcJGTMIqAurynqCVqRGmYubNQNpA
parking_slot:
  total_slots: 3
  hourly_rates: 10.0
profit:
  day: 0.0
  month: 0.0
  year: 0.0
