database_info:
  host: shortline.proxy.rlwy.net
  public_port: 24046
  database: railway
  user: root
  password: TyeCtcJGTMIqAurynqCVqRGmYubNQNpA
  
parking_slot:
  total_slots: 0
  hourly_rates: 10
